### PR TITLE
Better Predicates

### LINKED ISSUE #1016: [0.11.x] Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
I get this error when querying my GraphQL server after upgrading from `0.10.5` to `0.11.1`:

```
Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
W20170828-20:16:35.253(-4)? (STDERR)     at invariant (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/apollo-server-core/node_modules/graphql/jsutils/invariant.js:19:11)
W20170828-20:16:35.254(-4)? (STDERR)     at Object.validate (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/apollo-server-core/node_modules/graphql/validation/validate.js:60:72)
W20170828-20:16:35.254(-4)? (STDERR)     at doRunQuery (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/apollo-server-core/dist/runQuery.js:80:38)
W20170828-20:16:35.255(-4)? (STDERR)     at /Users/joncursi/Sites/joncursi/redbird-web/node_modules/apollo-server-core/dist/runQuery.js:20:54
W20170828-20:16:35.255(-4)? (STDERR)     at /Users/joncursi/.meteor/packages/promise/.0.10.0-beta.10.hrsya6.14jf9++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:39
```

My setup works great on `0.10.5`, and I don't see any related breaking changes in the `0.11.x` release notes. Any ideas on where to start troubleshooting this?

### PR DESCRIPTION
**Pull request by leebyron**
Introduces new predicate and assertion functions for each kind of type mirroring the existing ones for the higher order types. It also includes predicates for directives and schema. This should remove the need to use `instanceof` in any usage of GraphQL.js

This consolidates the checking of instances which generalizes the cross-realm/multiple-module check so that the clearer error message is provided in nearly all scenarios, reducing confusion.

This also replaces nearly all `instanceof` with new predicate functions internally.

Fixes #1134
Closes #1016

### CODE REVIEW

File: src/jsutils/instanceOf.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+  if (value instanceof constructor) {
+    return true;
+  }
+  if (value) {
+    const valueConstructor = value.constructor;
+    if (valueConstructor && valueConstructor.name === constructor.name) {
+      throw new Error(
+        `Cannot use ${constructor.name} "${value}" from another module or realm.
+
+Ensure that there is only one instance of "graphql" in the node_modules
```
Comment (IvanGoncharov) [inline src/jsutils/instanceOf.js]: @leebyron Not sure if anybody still using alternative package managers(e.g. bower) but maybe it worth to prefix this string with "If you are using NPM package" to reduce possible confusion.

File: src/type/definition.js [hunk 2]
```diff
@@ -66,6 +67,130 @@ export function assertType(type: mixed): GraphQLType {
...
+  GraphQLNonNull);
+// eslint-disable-next-line no-redeclare
+export function isNonNullType(type) {
+  return instanceOf(type, GraphQLNonNull);
+}
+
+export function assertNonNullType(type: mixed): GraphQLNonNull<any> {
+  invariant(
+    isNonNullType(type),
+    `Expected ${String(type)} to be a GraphQL Non-Null type.`,
```
Comment (IvanGoncharov) [inline src/type/definition.js]: @leebyron Maybe it worth to say something like `to be wrapped in`?
Same goes for List.

File: src/type/definition.js [hunk 3]
```diff
@@ -66,6 +67,130 @@ export function assertType(type: mixed): GraphQLType {
...
+
+export function assertListType(type: mixed): GraphQLList<any> {
+  invariant(
+    isListType(type),
+    `Expected ${String(type)} to be a GraphQL List type.`,
+  );
+  return type;
+}
+
+declare function isNonNullType(type: mixed): boolean %checks(type instanceof
```
Comment (IvanGoncharov) [inline src/type/definition.js]: @leebyron Since antagonist function called `isNullableType` maybe it worth to rename this one to `isNonNullableType`?

File: src/type/definition.js [hunk 4]
```diff
@@ -184,20 +303,36 @@ export function assertCompositeType(type: ?GraphQLType): GraphQLCompositeType {
...
+export type GraphQLWrappingType = GraphQLList<any> | GraphQLNonNull<any>;
+
+export function isWrappingType(type: mixed): boolean %checks {
+  return isListType(type) || isNonNullType(type);
+}
+
+export function assertWrappingType(type: mixed): GraphQLWrappingType {
+  invariant(
+    isWrappingType(type),
+    `Expected ${String(type)} to be a GraphQL wrapping type.`,
```
Comment (IvanGoncharov) [inline src/type/definition.js]: @leebyron Since this error messages are intended for developers who just use public API they can unfamiliar with what `wrapping type` means. Maybe it worth to replace it with something like  `to be a type wrapped by either NonNull or List wrapper`?
Similarly, other error messages will benefit from replacing composite terms like `leat type`, `abstract type`, `composite type`, etc.

File: src/utilities/astFromValue.js [hunk 5]
```diff
@@ -111,49 +111,49 @@ export function astFromValue(value: mixed, type: GraphQLInputType): ?ValueNode {
     return ({ kind: Kind.OBJECT, fields: fieldNodes }: ObjectValueNode);
   }
 
-  invariant(
-    type instanceof GraphQLScalarType || type instanceof GraphQLEnumType,
-    'Must provide Input Type, cannot use: ' + String(type),
-  );
+  if (isScalarType(type) || isEnumType(type)) {
```
Comment (IvanGoncharov) [inline src/utilities/astFromValue.js]: @leebyron Can it be replaced with `isLeafType`?

**Comment by jquense** [comment]
🎉 THANK YOU!
