### PR TITLE
Call 'toJSON' if present for ID and String serialize

### LINKED ISSUE #1518: Unable to query for MongoDB ObjectIDs
I recently updated from `0.13.2` to `14.0.2` which includes breaking changes.

This introduced errors with existing queries which include MongoDB Object Ids (probably from #1382):

> ID cannot represent value: { _bsontype: \"ObjectID\", id: <Buffer 5b 96 3d bf 98 0a 04 09 85 c6 6e a1> }

Repository with complete, minimal repeatable example [here](https://github.com/alexmcmillan/graphql-mongodb-query-fail-demo):

```
const Thing = mongoose.model('Thing', new mongoose.Schema({
  id: mongoose.Schema.Types.ObjectId,
  name: String
}));

const ThingType = new GraphQLObjectType({
  name: 'thing',
  fields: function () {
    return {
      id: { type: GraphQLID },
      name: { type: GraphQLString }
    }
  }
});

const RootMutation = new GraphQLObjectType({
  name: 'CreateMutation',
  fields: {
    create: {
      type: ThingType,
      description: 'Create new thing',
      args: {
        name: {
          name: 'Name of Thing',
          type: new GraphQLNonNull(GraphQLString)
        }
      },
      resolve: (root, args) => {
        const newThing = new Thing({ name: args.name });
        newThing.id = newThing._id;
        return new Promise((res, rej) => {
          newThing.save(err => {
            if (err) return rej(err);
            res(newThing);
          });
        });
      }
    }
  }
});
```

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Fixes #1518 

`class ObjectId` doesn't have `valueOf` only `toString` and `toJSON`:
https://github.com/mongodb/js-bson/blob/5acdebf7a63ed02d3bc1eb8481cdcb709fb5c886/lib/objectid.js#L213-L215

We can't use `toString` because:
```js
class A {}
const a = new A();
a.toString()
// '[object Object]'
```

So I added support for `toJSON`.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@alexmcmillan I don't have access to MongoDB so I can't run: https://github.com/alexmcmillan/graphql-mongodb-query-fail-demo

Can you please test it with attached package:
[graphql-14.0.2.zip](https://github.com/graphql/graphql-js/files/2372034/graphql-14.0.2.zip)
Just unpack it inside `node_modules`.

**Comment by alexmcmillan** [comment]
@IvanGoncharov Can confirm the package you attached does resolve the problem.  Thank you - I hope this gets merged soon!

**Comment by IvanGoncharov** [comment]
@alexmcmillan Thanks 👍 
@mjmahone Can you please review?
`mongoose` is a pretty popular library so I think it's worth to make `14.1.0`.
What do you think?

File: src/type/scalars.js [hunk 1]
```diff
@@ -117,24 +117,36 @@ export const GraphQLFloat = new GraphQLScalarType({
...
 });
 
-function serializeString(value: mixed): string {
-  // Support serializing objects with custom valueOf() functions - a common way
-  // to represent an complex value which can be represented as a string
-  // (ex: MongoDB id objects).
-  const result =
-    value && typeof value.valueOf === 'function' ? value.valueOf() : value;
+// Support serializing objects with custom toJSON() or valueOf() functions -
+// a common way to represent an complex value which can be represented as
```
Comment (mjmahone) [inline src/type/scalars.js]: grammar nit: "a complex value" instead of "an complex value"

Comment (IvanGoncharov) [reply src/type/scalars.js]: Thanks 👍 
Fixed

**Comment by IvanGoncharov** [comment]
> Prior to doing the bump to 14.1.0 I think we'd want @leebyron to help fix our NPM push process: I don't want to accidentally mess up another release, and I don't want Lee to be on the hook for overseeing and validating each patch

Agree, we definitely need to improve [bus factor](https://en.wikipedia.org/wiki/Bus_factor) 👍

> Can the version bump wait until the next WG meeting? 

Yes 👍 

> I'm not sure why this would be a minor release rather than a patch, and I don't currently have the right framework for figuring out that answer.

AFAIK, it covered by semver:
https://semver.org/#spec-item-7
> It MAY be incremented if substantial new functionality or improvements are introduced within the private code.

My personal rule of thumb: if you add something new that clients explicitly depend on it means you need to do `minor` release. So if someone write the resolvers that depend on `toJSON` that mean this will work only on `>= 14.1.0` and if for somereason we release `14.0.3` it wouldn't contain this feature.

It also important for 3rd tools like `graphql-tools` and other graphql middlewares since they wrapping resolvers and may be surprised by object with `toJSON` so they have an option to support only `14.0.x` and be shielded from new features.

So for me this change is not a bug fix but a new functionality especially since `0.13.x` and previous version didn't use `toJSON` (they used `toString`).

File: src/type/scalars.js [hunk 2]
```diff
@@ -117,24 +117,36 @@ export const GraphQLFloat = new GraphQLScalarType({
...
-  // Support serializing objects with custom valueOf() functions - a common way
-  // to represent an complex value which can be represented as a string
-  // (ex: MongoDB id objects).
-  const result =
-    value && typeof value.valueOf === 'function' ? value.valueOf() : value;
+// Support serializing objects with custom toJSON() or valueOf() functions -
+// a common way to represent a complex value which can be represented as
+// a string (ex: MongoDB id objects).
+function serializeObject(value: mixed): mixed {
+  if (typeof value === 'object' && value !== null) {
```
Comment (ruiaraujo) [inline src/type/scalars.js]: ```!= nulll```

Comment (IvanGoncharov) [reply src/type/scalars.js]:
```
> typeof undefined
'undefined'
```
@ruiaraujo So it will fail on the first check.

File: src/type/scalars.js [hunk 3]
```diff
@@ -117,24 +117,36 @@ export const GraphQLFloat = new GraphQLScalarType({
...
+    if (typeof value.toJSON === 'function') {
```
Comment (leebyron) [inline src/type/scalars.js]: This change is actually breaking - there may be objects which define *both* `valueOf` and `toJSON` which provide different values. If those objects previously worked correctly, this PR would cause them to work incorrectly.

If the goal is to also support objects which define `toJSON` but *do not* define `valueOf` then this could be easily solved by just moving this new addition to *below* the existing check for `valueOf`

Comment (IvanGoncharov) [reply src/type/scalars.js]: I did that because: 
```
> typeof ({}).valueOf
'function'
```
But I agree it breaking so I updated this PR to have this instead:
```js
    if (typeof value.valueOf === 'function') {
      const valueOfResult = value.valueOf();
      if (typeof valueOfResult !== 'object') {
        return valueOfResult;
      }
    }
    if (typeof value.toJSON === 'function') {
      return value.toJSON();
    }
```
I also changed tests to explicitly test precidence.
Can you please review new code and tests?

**Comment by IvanGoncharov** [comment]
@mjmahone Since you reviewed this PR and I already addressed @leebyron comments I merging this issue, so people can atleast use our `npm` branch.
Would be great to disscuss the scope for `14.1.0` release, can you please comment in #1543 ?

**Comment by frankRose1** [comment]
> I am having this problem also. Using "graphql": "^14.0.2"
> **"ID cannot represent value: { _bsontype: "ObjectID"**
> In a query resolver such as below, can someone explain what I do to fix it?
> Thanks
> 
> ```
>     user: async (parent, args, context, info) => {
>       let user = await context.UserModel.findOne(args);
>       return user;
>     }
> ```

I know its a bit of a late response but In regards to xabra's post try this:
```javascript
user: async(parent, args, ctx, info){
     let user = await ctx.UserModel.findOne(args);
     return { ...user._doc, _id: user._id.toString() };
}
```

**Comment by EmiyaYang** [comment]
> > I am having this problem also. Using "graphql": "^14.0.2"
> > **"ID cannot represent value: { _bsontype: "ObjectID"**
> > In a query resolver such as below, can someone explain what I do to fix it?
> > Thanks
> > ```
> >     user: async (parent, args, context, info) => {
> >       let user = await context.UserModel.findOne(args);
> >       return user;
> >     }
> > ```
> 
> I know its a bit of a late response but In regards to xabra's post try this:
> 
> ```js
> user: async(parent, args, ctx, info){
>      let user = await ctx.UserModel.findOne(args);
>      return { ...user._doc, _id: user._id.toString() };
> }
> ```

Well, I have no problems to query the _id field. But once I populate something I meet this error.

```ts
  function findOne(id: string) {
    const res = this.nodeModel.findOne({ id }).populate('parent');

    return res;
  }
```
