### PR TITLE
fix #1277 ensure interface has at least 1 concrete type

### LINKED ISSUE #1277: Throw error if no possible concrete types found
While using relay modern v1.5.0, I got the following when running relay-compiler (I promise this is a graphql issue):

```sh
ERROR:
Cannot read property 'some' of undefined
error An unexpected error occurred: "Command failed.
Exit code: 100
```
Note that the error has no stack trace!

The `some` that it mentioned was:
```js
	function hasConcreteTypeThatImplements(schema, type, interfaceName) {
	  return isAbstractType(type) && getConcreteTypes(schema, type).some(function (concreteType) {
	    return implementsInterface(concreteType, interfaceName);
	  });
	}
```

Ultimately, this was caused because when graphql built my schema, it crawled & found the GraphQLInterfaceType, but it didn't find the concrete types that implemented the interface.
This didn't throw an error in GraphQL; however, calling `schema.getPossibleTypes` returned `undefined`, which borked it in the compiler.

While it'd be nice for relay-compiler to catch errors & include a stack trace, I think the real issue is that GraphQL allows an abstract type to exist without any concrete types!

I propose closing this hole by calling schema.getPossibleTypes for each abstract type when building the schema. if the result is `undefined` then throw a friendly error telling the user to add that concrete type to their `rootSchema.types`.

Happy to PR if this sounds like a reasonable plan!

### PR DESCRIPTION
**Pull request by mattkrick**
Changes:

- [ ] `getPossibleTypes` is now guaranteed to return an array, just like its flow typing says it does
- [ ] Validation ensures each interface has at least 1 object type
- [ ] Conforms to Spec, Type Validation, Rule 4: https://github.com/facebook/graphql/pull/424

### CODE REVIEW

File: src/type/validate.js [hunk 1]
```diff
@@ -355,6 +358,21 @@ function validateObjectInterfaces(
...
+function validateInterfaces(
+  context: SchemaValidationContext,
+  iface: GraphQLInterfaceType,
+): void {
+  const possibleTypes = context.schema.getPossibleTypes(iface);
+
+  if (possibleTypes.length === 0) {
+    context.reportError(
+      `No concrete types found for Interface type ${iface.name}. ` +
+        `If only referenced via abstraction, add concrete types to schema.types array`,
```
Comment (IvanGoncharov) [inline src/type/validate.js]: The schema can be create using SDL syntax so `add concrete types to schema.types array` part would be confusing in such case.
`concrete types` - better to avoid inventing new terminology.

Something like this would be great:
`Interface ${iface.name} should be implemented by at least one object type.`
Disclaimer: I'm grammatically challenged 😄

Comment (mattkrick) [reply src/type/validate.js]: good call, fixed!

**Comment by mattkrick** [comment]
@IvanGoncharov ready for another review!

File: src/type/schema.js [hunk 2]
```diff
@@ -204,7 +207,7 @@ export class GraphQLSchema {
     if (!possibleTypeMap[abstractType.name]) {
       const possibleTypes = this.getPossibleTypes(abstractType);
       invariant(
-        Array.isArray(possibleTypes),
+        Array.isArray(possibleTypes) && possibleTypes.length > 0,
```
Comment (leebyron) [inline src/type/schema.js]: This is a late checking invariant, not part of the scheme validation. This change shouldn't be necessary

Comment (mattkrick) [reply src/type/schema.js]: @leebyron this was only necessary for getting the schema tests working

Comment (mattkrick) [reply src/type/schema.js]: Fully agree. The invariant can go away because `getPossibleTypes` is now guaranteed to return an array.
The test can go away because there's no way `isPossibleType` can produce an error.

File: src/type/__tests__/schema-test.js [hunk 3]
```diff
@@ -76,19 +76,6 @@ const Schema = new GraphQLSchema({
 });
 
 describe('Type System: Schema', () => {
-  describe('Getting possible types', () => {
```
Comment (mattkrick) [inline src/type/__tests__/schema-test.js]: `isPossibleType` can no longer throw, so this test is no longer needed

File: src/type/schema.js [hunk 4]
```diff
@@ -159,6 +160,8 @@ export class GraphQLSchema {
             this._implementations[iface.name] = [type];
           }
         });
+      } else if (isAbstractType(type) && !this._implementations[type.name]) {
+        this._implementations[type.name] = [];
```
Comment (mattkrick) [inline src/type/schema.js]: guarantees that `getPossibleTypes` returns an array, as it should per its flow type.

**Comment by mattkrick** [comment]
@leebyron that should fix it up

File: src/type/validate.js [hunk 5]
```diff
@@ -355,6 +358,21 @@ function validateObjectInterfaces(
...
 
+function validateInterfaces(
+  context: SchemaValidationContext,
+  iface: GraphQLInterfaceType,
+): void {
+  const possibleTypes = context.schema.getPossibleTypes(iface);
+
+  if (possibleTypes.length === 0) {
+    context.reportError(
+      `Interface ${iface.name} must be implemented` +
```
Comment (leebyron) [inline src/type/validate.js]: Could you please expand the tests further to include a test which asserts this error occurs?

**Comment by leebyron** [comment]
Great work!
